groups:
  - name: example
    rules:
      - alert: InstanceDown
        # Based on https://prometheus.io/docs/prometheus/latest/configuration/template_examples/
        expr: up == 0
        for: 10s
        labels:
          severity: page
        annotations:
          summary: "Instance {{$labels.instance}} down"
          description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 10 seconds."
