apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: invoice-app
  namespace: store
  labels:
    team: store
spec:
  selector:
    matchLabels:
      app: invoice
  endpoints:
    - port: web
      path: /prometheusMetrics
